### ISSUE TITLE
Dataset for shoe detection

### ISSUE THREAD

**Issue by ShucongYin** [ibaiGorordo/shoeDetection#2]
I want to use the dataset to train my model for shoe detection. Could you share the dataset that you used in your paper? @ibaiGorordo

**Comment by ibaiGorordo** [comment]
Hi,

I will answer here for future reference, I used the OpenImages dataset for the "footwear" label. I have not tried it, but you can check this tutorial on how to download those images only (https://towardsdatascience.com/how-to-easily-download-googles-open-images-dataset-for-your-ai-apps-db552a82fc6), and you will probably find this tutorial also interesting: https://medium.com/mlearning-ai/multiple-object-detection-using-nvidias-transfer-learning-toolkit-e7cfc1b5a381

In my case I only kept the images where the foot was big (based on the relative size of the bounding box).

**Comment by ShucongYin** [comment]
Hi

Do you use the method(https://towardsdatascience.com/how-to-easily-download-googles-open-images-dataset-for-your-ai-apps-db552a82fc6) successfully? I input the command but there are some errors, for example "ConnectionReseError: [Errno 104] Connection reset by peer". I want to know how to slove it.
@ibaiGorordo

**Comment by ShucongYin** [comment]
Hi,

Do you still have the dataset that you used to train your model? Can you share it on somewhere? @ibaiGorordo

**Comment by ibaiGorordo** [comment]
I didn't, I did it manually, using the links in the .csv with the info in the dataset, but probably if you search about it there is probably an updated info on how to do the same as in the tutorial.

**Comment by ibaiGorordo** [comment]
I only have the Tensorflow .record files for the training and testing, I do not have the raw images anymore.

**Comment by ShucongYin** [comment]
> I only have the Tensorflow .record files for the training and testing, I do not have the raw images anymore.

I think the tf.record files maybe is OK. Could you share it?

**Comment by ibaiGorordo** [comment]
**train.record**: https://drive.google.com/file/d/1OXtOd2-E2uCiySFmNkV9ihXHXG-LBGpW/view?usp=sharing
**test.record**: https://drive.google.com/file/d/1StewrFsqR00YBGiMFzv1oxKyiqegk3PR/view?usp=sharing
**labelMap**: https://drive.google.com/file/d/1D4ChQD-SM8Ol0Ra8judtvs416LdLW3Yn/view?usp=sharing

**Comment by ShucongYin** [comment]
> **train.record**: https://drive.google.com/file/d/1OXtOd2-E2uCiySFmNkV9ihXHXG-LBGpW/view?usp=sharing
> **test.record**: https://drive.google.com/file/d/1StewrFsqR00YBGiMFzv1oxKyiqegk3PR/view?usp=sharing
> **labelMap**: https://drive.google.com/file/d/1D4ChQD-SM8Ol0Ra8judtvs416LdLW3Yn/view?usp=sharing

Thank you very much! I will have a try.

**Comment by ibaiGorordo** [comment]
Good luck!

Closing this issue for now, let me know if you find any problem.

**Comment by ShucongYin** [comment]
> Good luck!
> 
> Closing this issue for now, let me know if you find any problem.

Oh, it was unsuccessful, I guess it may be because YOLO and SSD require different label formats.

**Comment by ShucongYin** [comment]
> I didn't, I did it manually, using the links in the .csv with the info in the dataset, but probably if you search about it there is probably an updated info on how to do the same as in the tutorial.

So could you tell me how to manually download it? @ibaiGorordo

**Comment by ibaiGorordo** [comment]
Go to the openimages dataset (https://storage.googleapis.com/openimages/web/download.html) and download the "Image IDs" files with the original links for the images. 

You will have to parse the file with the object id from the "Image labels" file to know which images have shoes on them.

So, that is why I recommend you to find a tutorial that shows how to do that automatically.

**Comment by ShucongYin** [comment]
> Go to the openimages dataset (https://storage.googleapis.com/openimages/web/download.html) and download the "Image IDs" files with the original links for the images.
> 
> You will have to parse the file with the object id from the "Image labels" file to know which images have shoes on them.
> 
> So, that is why I recommend you to find a tutorial that shows how to do that automatically.

OK, thank you!
